/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, Decal, useTexture } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Orange = (props) => {
  const orangeRef = useRef();
  const { nodes, materials } = useGLTF('/orange.glb');

  const decalTexture = useTexture('/sticker-3.png');
  decalTexture.flipY = false;

  const position = props.position ?? [3.75, 3.75, 0];

  materials.apple.metalness = 0.8;
  materials.apple.roughness = 0.2;

  materials.apple2.metalness = 0.6;
  materials.apple.color = {
    r: 1,
    g: 0.3,
    b: 0,
    isColor: true
  };

  useFrame(({clock}) => {
    orangeRef.current.rotation.y = clock.elapsedTime / 2;
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.25} position={position} ref={orangeRef} rotation={[0.7, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials.apple}
        >  
          <Decal
            position={[-0.2, 1.1, 1.2]}
            rotation={[2.5, 0.7, 0.1]}
            scale={[0.7, 0.7, 0.7]}
          >
            <meshBasicMaterial
              map={decalTexture}
              polygonOffset
              polygonOffsetFactor={-1}
              transparent={true}
              depthTest={false}
            />
          </Decal>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_2.geometry}
          material={materials.apple2}
        >
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload('/orange.glb')

export default Orange;