/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Banana = (props) => {
  const bananaRef = useRef();
  const { nodes, materials } = useGLTF('/banana.glb');

  const position = props.position ?? [6, 2,-3];
  const rotation = props.rotation ?? [0,0,0];

  materials['Material.001'].metalness = 0.6;

  useFrame(({clock}) => {
    bananaRef.current.rotation.y = clock.elapsedTime;
  });

  return (
    <group {...props} dispose={null} scale={0.25} rotation={rotation} position={position} ref={bananaRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
      />
    </group>
  );
};

useGLTF.preload('/banana.glb');

export default Banana;
